# Zero Trust ICS ACLs
# This file is managed by acl_manager.py.

user ics-server
topic write ics/control/#
topic read ics/telemetry/#
topic read ics/alerts/#

# BEGIN DEVICE ESP32_001
user ESP32_001
topic read ics/control/ESP32_001
topic write ics/telemetry/ESP32_001
topic write ics/alerts/ESP32_001
# END DEVICE ESP32_001
