# Zero Trust ICS MQTT broker

persistence true
persistence_location /var/lib/mosquitto/
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

per_listener_settings true
listener 8883
protocol mqtt
allow_anonymous false
acl_file /etc/mosquitto/acl.conf
tls_version tlsv1.3
cafile /etc/mosquitto/certs/root-ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
